import type { Metadata } from 'next'
import Posts from './../../components/posts'

export const metadata: Metadata = {
  title: 'Post',
  description: 'Generated by create next app',
}

const loadPosts = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts');
  return await response.json();
}

export default async function Post() {
  const posts = await loadPosts();

  return (
    <section>
      <h1>Post Page</h1>
      <Posts posts={posts} />
    </section>
  )
}