import type { Metadata } from 'next'
import Posts from './../../components/Posts'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <section>
      <h1>About Page</h1>
      <Posts />
    </section>
  )
}