import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <section>
      <h1>About Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore nihil inventore veniam nisi a. Nostrum odio voluptatum quam itaque voluptatem et, adipisci expedita dolorem cupiditate, at illo esse! Eaque, voluptatem.</p>
    </section>
  )
}