import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es-VE">
      <body className={inter.className}>
        <Link href={'/'}>Home</Link>|
        <Link href={'/about'}>About</Link>
        <article>{children}</article>
      </body>
    </html>
  )
}
