import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Nunito } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Todo Next',
  description: 'Generated by create next app',
}

const nunito = Nunito({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es-VE">
      <body className={nunito.className}>
        <article className="text-center">
          <Link href={'/'} className='mr-4 uppercase'>Home</Link>
          <Link href={'/about'} className='mr-4 uppercase'>About</Link>
          <Link href={'/post'} className='uppercase'>Post</Link>
        </article>
        <main className='flex min-h-screen flex-col items-center justify-between p-24'>{children}</main>
      </body>
    </html>
  )
}
