import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <section>
      <h1>Home Page</h1>
    </section>
  )
}
